#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# windows_registry_key - Windows Registry Key
#
# Copyright (C) 2020 Sam Daenen <sam.daenen@continu-it.be>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

def windowsregistrykey_name(line):
    join = ' '.join(line).split('|')
    return join[0]

def inventory_windows_registry_key(info):
    for line in info:
        yield windowsregistrykey_name(line), {}

def check_windows_registry_key(item, params, info): 
    for line in info:
        if item == windowsregistrykey_name(line):
            if params:
                keyvalueparams = params.get('keyvalue')             
                keyvalue = ' '.join(line).split('|')[1]
                if keyvalue in keyvalueparams:
                    yield 0, keyvalue
                else:
                    yield 2, keyvalue + " is not the set parameter"
            else:
                yield 3, "No parameters have been set for this Registry Key. Got :" + ' '.join(line).split('|')[1]

check_info['windows_registry_key'] = {
    'check_function':      check_windows_registry_key,
    'service_description': "Registry key %s",
    'has_perfdata':        True,
    'inventory_function':  inventory_windows_registry_key,
    'group':               'windows_registry_key',
}
